env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: 0,
  no-param-reassign: 0,
}
